# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o set.o
LINKOBJ  = main.o set.o
LIBS     = -L"C:/Users/HP/Desktop/BSIT/IMPORTANT APP!!!/Dev-Cpp/MinGW64/lib32" -L"C:/Users/HP/Desktop/BSIT/IMPORTANT APP!!!/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -pg
INCS     = -I"C:/Users/HP/Desktop/BSIT/IMPORTANT APP!!!/Dev-Cpp/MinGW64/include" -I"C:/Users/HP/Desktop/BSIT/IMPORTANT APP!!!/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/HP/Desktop/BSIT/IMPORTANT APP!!!/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/HP/Desktop/BSIT/IMPORTANT APP!!!/Dev-Cpp/MinGW64/include" -I"C:/Users/HP/Desktop/BSIT/IMPORTANT APP!!!/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/HP/Desktop/BSIT/IMPORTANT APP!!!/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/HP/Desktop/BSIT/IMPORTANT APP!!!/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = SetList.exe
CXXFLAGS = $(CXXINCS) -m32 -pg
CFLAGS   = $(INCS) -m32 -pg
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

set.o: set.c
	$(CC) -c set.c -o set.o $(CFLAGS)
